//Question 23: Conditional Tests: Write a series of conditional tests. Predict the results of each test.
var car = "saburu";
console.log("is car == 'saburu'? predict true");
console.log(car == 'saburu');
console.log("is car != 'honda city'? predict true");
console.log(car != 'honda city');
console.log("is car == 'Saburu'? predict false");
console.log(car == 'Saburu');
console.log("is car == 'SABURU'? predict false");
console.log(car == 'SABURU');
console.log("is car.length == 6? predict true");
console.log(car.length == 6);
console.log("is 10 > 45 ? predict false");
console.log(10 > 45);
console.log("is car.length == 10? predict true");
console.log(car.length != 10);
console.log("is 3 <= 2 ? predict false");
console.log(3 <= 2);
console.log("is 54 <= 51 ? predict true");
console.log(3 > 2);
console.log("is car == 'saburu' && car.length == 6? predict false");
console.log(car == 'saburu' && car.length == 7);
